- name: Create GCP instance from template
  gcp_compute_instance_template:
    project: "{{ project }}"
    auth_kind: "{{ auth_kind }}"
    service_account_file: "{{ service_account_file }}"
    zone: "{{ zone }}"
    name: "{{ item }}"
    source_instance_template: "{{ group_name }}"
    metadata: '{"ssh-keys":"ansible:{{ authorized_keys }}"}'

  with_items: "{{ groups[group_name] }}"
  when: "existing_instances is defined or item not in existing_instances.results | map(attribute='name') | list"